# Generated by Django 2.2.3 on 2019-07-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('catalog_category_phone', models.ManyToManyField(blank=True, related_name='category_phone_catalog', to='blog.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Category_a_laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('catalog_category_a_laptop', models.ManyToManyField(blank=True, related_name='category_a_laptop_catalog', to='blog.Catalog')),
            ],
        ),
    ]
