# Generated by Django 2.2.3 on 2019-07-26 20:36

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_a_laptop_category_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(db_index=True, upload_to=blog.models.media)),
                ('camera', models.CharField(blank=True, db_index=True, max_length=50)),
                ('memory', models.CharField(blank=True, db_index=True, max_length=50)),
                ('thach_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('cairt_sim', models.CharField(blank=True, db_index=True, max_length=50)),
                ('accessory', models.CharField(blank=True, db_index=True, max_length=50)),
                ('decimal', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('product_phone_catalog', models.ManyToManyField(blank=True, related_name='catalog_product_phone', to='blog.Catalog')),
                ('product_phone_category', models.ManyToManyField(blank=True, related_name='category_product_phone', to='blog.Category_Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Product_a_laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(db_index=True, upload_to=blog.models.media)),
                ('weight', models.CharField(blank=True, db_index=True, max_length=30)),
                ('memory', models.CharField(blank=True, db_index=True, max_length=30)),
                ('ssd', models.CharField(blank=True, db_index=True, max_length=30)),
                ('touch', models.CharField(blank=True, db_index=True, max_length=30)),
                ('accessory', models.CharField(blank=True, db_index=True, max_length=50)),
                ('decimal', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('product_a_laptop_catalog', models.ManyToManyField(blank=True, related_name='catalog_product_a_laptop', to='blog.Catalog')),
                ('product_a_laptop_category', models.ManyToManyField(blank=True, related_name='category_product_a_laptop', to='blog.Category_a_laptop')),
            ],
        ),
    ]
